### ISSUE TITLE
HW06: Ошибка при наличии пробелов в начале программы

### ISSUE THREAD

**Issue by kajigor** [23jura23/hse20_formalang#2]
[tm02.txt](https://github.com/23jura23/hse20_formalang/files/5392299/tm02.txt)

```
(line 1, column 1):
unexpected " "
expecting "module"
```

**Comment by 23jura23** [comment]
Пробелы в начале программы обрабатываются не парсером `modul`, а парсером `program`, поэтому если отдельно тестировать `modul`, то он пробелы в начале не будет опускать, тогда как целиком этот файл принимается парсером

**Comment by kajigor** [comment]
Да, действительно.
